### ISSUE TITLE
In adapter-fine-tuning, why don't fix original params?

### ISSUE THREAD

**Issue by zihaolucky** [google-research/adapter-bert#2]
Hi guys,

I have a glance at the `run_classifier.py` code and didn't see the code for fixing original transformer parameters, so it's full fine-tune setting, and why? Thanks~

**Comment by ghost** [comment]
@zihaolucky The restriction to training only parameters in the adapters, layer-norm, and head is made in the optimizer, using collections:

```
tvars = []
for collection in ["adapters", "layer_norm", "head"]:
  tvars += tf.get_collection(collection)
```

**Comment by zihaolucky** [comment]
@neil-houlsby Get it. Thank you!
